---
title: "1960s_ARULES_DTree"
author: "Barrett Ray"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Setup

```{r}
library(ggplot2)
library(tidyverse)
Data_1960 <- read.csv('spotify_1960s.csv')

spotify_1960s = Data_1960[,-c(1:4,8:10,24:25)]

ggplot(data=Data_1960, aes(x=popularity)) + geom_histogram() + theme_bw()
ggplot(data=Data_1960, aes(x=duration_ms)) + geom_histogram() + theme_bw()
ggplot(data=Data_1960, aes(x=as.factor(year),y=popularity)) + geom_boxplot() + theme_bw()

summary_df_1960 <- Data_1960 %>% 
                      group_by(year) %>% 
                      summarise(AvgPop = mean(popularity, na.rm = TRUE),
                            AvgArtPop = mean(artist_popularity, na.rm = TRUE),
                            AvgFollow = mean(followers, na.rm = TRUE),
                            AvgTempo = mean(tempo, na.rm = TRUE),
                            AvgDance = mean(danceability, na.rm = TRUE),
                            AvgEnergy = mean(energy, na.rm = TRUE),
                            AvgDur = mean(duration_ms, na.rm = TRUE),
                            NumExp = sum(explicit),
                            NumArtists = length(unique(id_artists)))
```

## Variable Discretation

```{r}
library(arules)
## Song Popularity
summary(spotify_1960s$popularity)
summary(discretize(spotify_1960s$popularity,breaks=2))
x <- spotify_1960s$popularity
summary( cut(x,c(-1,16,83)))
x <-cut(x,c(-1,16,83))
levels(x) <- c("Low","High")
spotify_1960s$popularity <- x

## Duration
summary(spotify_1960s$duration_ms)
summary(discretize(spotify_1960s$duration_ms, breaks = 5))
x <- spotify_1960s$duration_ms
summary( cut(x,c(23200,142000,165000,192000,246000,3580000)))
x <-cut(x,c(23200,142000,165000,192000,246000,3580000))
levels(x) <- c("23200 to 142000","142000 to 165000","165000 to 192000",
               "192000 to 246000","246000 to 3580000")
spotify_1960s$duration_ms <- x

## Explicit
summary(spotify_1960s$explicit)
summary(as.factor(spotify_1960s$explicit))
spotify_1960s$explicit <- as.factor(spotify_1960s$explicit)

## Danceability
summary(spotify_1960s$danceability)
summary(discretize(spotify_1960s$danceability, breaks = 5))
x <- spotify_1960s$danceability
summary( cut(x,c(-1,0.2,0.4,0.6,0.8,1)))
x <- cut(x,c(-1,0.2,0.4,0.6,0.8,1))
levels(x) <- c("0 to 0.2","0.2 to 0.4","0.4 to 0.6",
               "0.6 to 0.8","0.8 to 1")
spotify_1960s$danceability <- x

## Energy
summary(spotify_1960s$energy)
summary(discretize(spotify_1960s$energy, breaks = 5))
x <- spotify_1960s$energy
summary( cut(x,c(-1,0.2,0.4,0.6,0.8,1)))
x <- cut(x,c(-1,0.2,0.4,0.6,0.8,11))
levels(x) <- c("0 to 0.2","0.2 to 0.4","0.4 to 0.6",
               "0.6 to 0.8","0.8 to 1")
spotify_1960s$energy <- x

## Key
summary(spotify_1960s$key)
table(spotify_1960s$key)
summary(discretize(spotify_1960s$key, breaks = 5))
spotify_1960s$key <- as.factor(spotify_1960s$key)

## Loudness
summary(spotify_1960s$loudness)
summary(discretize(spotify_1960s$loudness, breaks = 5))
x <- spotify_1960s$loudness
summary( cut(x,c(-60,-16,-13,-10,-8,6)))
x <- cut(x,c(-60,-16,-13,-10,-8,6))
levels(x) <- c("-60 to -16","-16 to -13","-13 to -10",
               "-10 to -8","-8 to 6")
spotify_1960s$loudness <- x

## Mode
table(spotify_1960s$mode)
spotify_1960s$mode <- as.factor(spotify_1960s$mode)

## Speachiness
summary(spotify_1960s$speechiness)
summary(discretize(spotify_1960s$speechiness, breaks = 5))
x <- spotify_1960s$speechiness
summary( cut(x, c(-1,0.032,0.037,0.045,0.065,1)))
x <- cut(x, c(-1,0.032,0.037,0.045,0.065,1))
levels(x) <- c("0 to 0.032","0.032 to 0.037","0.037 to 0.045",
               "0.045 to 0.065","0.065 to 1")
spotify_1960s$speechiness <- x

## Acousticness
summary(spotify_1960s$acousticness)
summary(discretize(spotify_1960s$acousticness, breaks = 5))
x <- spotify_1960s$acousticness
summary( cut(x, c(-1,0.45,0.7,0.83,0.93,1)))
x <- cut(x, c(-1,0.45,0.7,0.83,0.93,1))
levels(x) <- c("0 to 0.45","0.45 to 0.7","0.7 to 0.83",
               "0.83 to 0.93","0.93 to 1")
spotify_1960s$acousticness <- x

## Instrumentalness
summary(spotify_1960s$instrumentalness)
summary(discretize(spotify_1960s$instrumentalness, breaks = 5))
x <- spotify_1960s$instrumentalness
summary( cut(x, c(-1,0.0000175,0.0013,0.3,1)))
x <- cut(x, c(-1,0.0000175,0.0013,0.3,1))
levels(x) <- c("0 to 0.0000175","0.0000175 to 0.0013",
               "0.0013 to 0.3","0.3 to 1")
spotify_1960s$instrumentalness <- x

## Liveness
summary(spotify_1960s$liveness)
summary(discretize(spotify_1960s$liveness, breaks = 5))
x <- spotify_1960s$liveness
summary( cut(x,c(-1,0.095,0.12,0.18,0.325,1)))
x <- cut(x,c(-1,0.095,0.12,0.18,0.325,1))
levels(x) <- c("0 to 0.095","0.095 to 0.12","0.12 to 0.18",
               "0.18 to 0.325","0.325 to 1")
spotify_1960s$liveness <- x

## Valence 
summary(spotify_1960s$valence)
summary(discretize(spotify_1960s$valence, breaks = 5))
x <- spotify_1960s$valence
summary( cut(x, c(-1,0.3,0.5,0.66,0.82,1)))
x <- cut(x, c(-1,0.3,0.5,0.66,0.82,1))
levels(x) <- c("0 to 0.3","0.3 to 0.5","0.5 to 0.66",
               "0.66 to 0.82","0.82 to 1")
spotify_1960s$valence <- x

## Tempo
summary(spotify_1960s$tempo)
summary(discretize(spotify_1960s$tempo, beaks = 5))
x <- spotify_1960s$tempo
summary( cut(x,c(-1,98,124,241)))
x <- cut(x,c(-1,98,124,241))
levels(x) <- c("< 98","98 to 124","> 124")
spotify_1960s$tempo <- x

## Time Signature
summary(spotify_1960s$time_signature)
table(spotify_1960s$time_signature)
x <- spotify_1960s$time_signature
summary( cut(x, c(-1,3,4,5)))
x <- cut(x, c(-1,3,4,5))
levels(x) <- c("< 3","3 to 4","> 4")
spotify_1960s$time_signature <- x

## Followers
summary(spotify_1960s$followers)
summary(discretize(spotify_1960s$followers, breaks = 5))
x <- spotify_1960s$followers
summary( cut(x, c(-1,6500,54200,225000,1070000,19200000)))
x <- cut(x, c(-1,6500,54200,225000,1070000,19200000))
levels(x) <- c("0 to 6500","6500 to 54200","54200 to 225000","225000 to 1070000",
               "1070000 to 19200000")
spotify_1960s$followers <- x

## Artist Popularity
summary(spotify_1960s$artist_popularity)
summary(discretize(spotify_1960s$artist_popularity, breaks = 5))
x <- spotify_1960s$artist_popularity
summary( cut(x, c(-1,33,48,58,67,88)))
x <- cut(x, c(-1,33,48,58,67,88))
levels(x) <- c("0 to 33","33 to 48","48 to 58","58 to 67","67 to 88")
spotify_1960s$artist_popularity <- x

## Year
table(spotify_1960s$year)
spotify_1960s$year <- as.factor(spotify_1960s$year)
class(spotify_1960s$year)
```

## Factor Analysis

```{r}
library(rpart)

Trans <- as(spotify_1960s, "transactions")
summary(Trans)
itemFrequency(Trans)["popularity=High"]
RULES <- apriori(Trans,parameter = list(supp=200/length(Trans),conf=0.90,maxlen=4),
                 appearance = list(default="lhs",rhs="popularity=High"), control=list(verbose=FALSE))
RULES <- RULES[!is.redundant(RULES)]
RULES <- RULES[is.significant(RULES,Trans)]
length(RULES)
inspect(sort(RULES,by="confidence"))


TREE <- rpart(popularity ~ .,data=spotify_1960s)
TREE$cptable
summarize_tree(TREE)
visualize_model(TREE)
```

